//! lunaric.dev — a personal security/dev blog.
//! Hand-written in Rust, compiled to WebAssembly, served from Cloudflare's edge.

use comrak::{markdown_to_html, Options};
use serde::Deserialize;
use worker::wasm_bindgen::JsValue;
use worker::*;

// Generated by build.rs: `RAW_POSTS: &[(&str, &str)]` of (slug, raw markdown).
include!(concat!(env!("OUT_DIR"), "/posts_generated.rs"));

#[event(fetch)]
async fn fetch(req: Request, env: Env, ctx: Context) -> Result<Response> {
    console_error_panic_hook::set_once();

    // capture request metadata before the router consumes `req`
    let method = req.inner().method();
    let path = req.path();
    let ua = req.headers().get("user-agent").ok().flatten().unwrap_or_default();
    let ip = req.headers().get("cf-connecting-ip").ok().flatten().unwrap_or_default();
    let country = req.headers().get("cf-ipcountry").ok().flatten().unwrap_or_default();
    let log_db = env.d1("DB").ok();
    // the monitor's secret path lives in a Worker secret, so it's never in the repo
    let dash = env
        .secret("DASH_PATH")
        .map(|s| s.to_string())
        .ok()
        .filter(|s| s.starts_with('/'))
        .unwrap_or_else(|| "/__dash-unset".to_string());

    let resp = Router::new()
        .get("/", |_, _| Response::from_html(home_page()))
        .get("/whoami", |_, _| Response::from_html(layout("whoami", "whoami", SITE_DESC, "/whoami", "", WHOAMI)))
        .get("/blog", |_, _| Response::from_html(blog_index()))
        .get_async("/blog/:slug", |_, ctx| async move {
            let slug = match ctx.param("slug") {
                Some(s) => s.clone(),
                None => return Response::error("Not found", 404),
            };
            match find_post(&slug) {
                Some(p) => {
                    let views = bump_views(&ctx.env, &slug).await.unwrap_or(0);
                    Response::from_html(post_page(&p, views))
                }
                None => Response::error("Post not found", 404),
            }
        })
        .get("/projects", |_, _| Response::from_html(layout("projects", "projects", "Things I've built and broken.", "/projects", "", PROJECTS)))
        .get("/uses", |_, _| Response::from_html(layout("uses", "uses", "The gear and setup behind my homelab.", "/uses", "", USES)))
        .get_async("/guestbook", |_, ctx| async move {
            let entries = list_guestbook(&ctx.env).await.unwrap_or_default();
            Response::from_html(guestbook_page(&entries))
        })
        .post_async("/guestbook", |mut req, ctx| async move {
            let form = req.form_data().await?;
            // honeypot: real users never fill this hidden field; bots do.
            if !field(&form, "website").trim().is_empty() {
                return redirect_to("/guestbook");
            }
            let name = field(&form, "name");
            let message = field(&form, "message");
            if !message.trim().is_empty() {
                let _ = add_guestbook(&ctx.env, &name, &message).await;
            }
            redirect_to("/guestbook")
        })
        .get("/rss.xml", |_, _| {
            let mut r = Response::ok(rss())?;
            r.headers_mut().set("content-type", "application/rss+xml; charset=utf-8")?;
            Ok(r)
        })
        .get("/sitemap.xml", |_, _| {
            let mut r = Response::ok(sitemap())?;
            r.headers_mut().set("content-type", "application/xml; charset=utf-8")?;
            Ok(r)
        })
        .get("/robots.txt", |_, _| {
            let mut r = Response::ok("User-agent: *\nAllow: /\nSitemap: https://lunaric.dev/sitemap.xml\n")?;
            r.headers_mut().set("content-type", "text/plain; charset=utf-8")?;
            Ok(r)
        })
        .get_async("/api/ping", |_, _| async move {
            let body = r#"{"status":"ok","host":"lunaric.dev","runtime":"rust+wasm @ cloudflare edge"}"#;
            let mut resp = Response::ok(body)?;
            resp.headers_mut().set("content-type", "application/json")?;
            Ok(resp)
        })
        .post_async("/api/hit", |mut req, ctx| async move {
            let path = req.text().await.unwrap_or_default();
            if valid_path(&path) {
                let _ = record_hit(&ctx.env, &path).await;
            }
            Response::ok("")
        })
        .get_async("/stats", |_, ctx| async move {
            let rows = list_hits(&ctx.env).await.unwrap_or_default();
            Response::from_html(stats_page(&rows))
        })
        .get_async(&dash, |req, ctx| async move {
            // Cloudflare Access injects this header only for authenticated users.
            match req.headers().get("cf-access-authenticated-user-email").ok().flatten() {
                Some(email) => {
                    let data = dashboard_data(&ctx.env).await.unwrap_or_default();
                    Response::from_html(dashboard_page(&data, &email))
                }
                // unauthenticated (or Access not in front): look like any other 404
                None => Ok(not_found()),
            }
        })
        .run(req, env)
        .await?;
    let resp = if resp.status_code() == 404 { not_found() } else { resp };

    // log the request in the background (doesn't delay the response)
    if let Some(db) = log_db {
        if should_log(&path, &dash) {
            let status = resp.status_code();
            let threat = threat_tag(&path);
            ctx.wait_until(async move {
                let _ = log_request(&db, &method, &path, status, &country, &ip, &ua, threat).await;
            });
        }
    }
    Ok(secure(resp))
}

#[event(scheduled)]
async fn scheduled(_event: ScheduledEvent, env: Env, _ctx: ScheduleContext) {
    if let Ok(db) = env.d1("DB") {
        let _ = db
            .prepare("DELETE FROM requests WHERE id <= (SELECT MAX(id) FROM requests) - 5000")
            .run()
            .await;
    }
}

fn not_found() -> Response {
    let inner = r#"<h1>404 <span class="accent">// not found</span></h1>
<p class="lead">This path doesn't exist — or you don't have clearance.</p>
<p>Head back to <a href="/">~</a>, or try <a href="/blog">/blog</a> and <a href="/whoami">/whoami</a>.</p>"#;
    let html = layout("", "404", "Page not found.", "/404", "", inner);
    match Response::from_html(html) {
        Ok(r) => r.with_status(404),
        Err(_) => Response::error("Not found", 404).unwrap(),
    }
}

// ---------- security headers ----------

// Sources allowed: own origin, Google Fonts (CSS + font files), and cdnjs for
// highlight.js (script + theme). No inline scripts/styles → no 'unsafe-inline'.
const CSP: &str = "default-src 'self'; \
    script-src 'self'; \
    style-src 'self'; \
    font-src 'self'; \
    img-src 'self' data: https:; \
    connect-src 'self'; \
    base-uri 'none'; \
    form-action 'self'; \
    frame-ancestors 'none'; \
    object-src 'none'; \
    upgrade-insecure-requests";

fn secure(mut resp: Response) -> Response {
    let h = resp.headers_mut();
    let _ = h.set("Content-Security-Policy", CSP);
    let _ = h.set("X-Content-Type-Options", "nosniff");
    let _ = h.set("X-Frame-Options", "DENY");
    let _ = h.set("Referrer-Policy", "strict-origin-when-cross-origin");
    let _ = h.set(
        "Permissions-Policy",
        "geolocation=(), microphone=(), camera=(), payment=(), usb=(), interest-cohort=()",
    );
    let _ = h.set("Strict-Transport-Security", "max-age=63072000; includeSubDomains");
    let _ = h.set("Cross-Origin-Opener-Policy", "same-origin");
    resp
}

// ---------- D1: view counter + guestbook ----------

async fn bump_views(env: &Env, slug: &str) -> Result<i64> {
    let db = env.d1("DB")?;
    let count: Option<i64> = db
        .prepare(
            "INSERT INTO views (slug, count) VALUES (?1, 1) \
             ON CONFLICT(slug) DO UPDATE SET count = count + 1 RETURNING count",
        )
        .bind(&[JsValue::from(slug)])?
        .first(Some("count"))
        .await?;
    Ok(count.unwrap_or(0))
}

#[derive(Deserialize, Default)]
struct Entry {
    name: String,
    message: String,
    created: String,
}

async fn list_guestbook(env: &Env) -> Result<Vec<Entry>> {
    let db = env.d1("DB")?;
    db.prepare("SELECT name, message, created FROM guestbook ORDER BY id DESC LIMIT 100")
        .all()
        .await?
        .results::<Entry>()
}

async fn add_guestbook(env: &Env, name: &str, message: &str) -> Result<()> {
    let db = env.d1("DB")?;
    let mut name = clamp(name.trim(), 50);
    if name.is_empty() {
        name = "anonymous".to_string();
    }
    let message = clamp(message.trim(), 1000);
    db.prepare("INSERT INTO guestbook (name, message) VALUES (?1, ?2)")
        .bind(&[JsValue::from(name), JsValue::from(message)])?
        .run()
        .await?;
    Ok(())
}

async fn record_hit(env: &Env, path: &str) -> Result<()> {
    let db = env.d1("DB")?;
    db.prepare("INSERT INTO hits (path, count) VALUES (?1, 1) ON CONFLICT(path) DO UPDATE SET count = count + 1")
        .bind(&[JsValue::from(path)])?
        .run()
        .await?;
    Ok(())
}

#[derive(Deserialize, Default)]
struct Hit {
    path: String,
    count: i64,
}

async fn list_hits(env: &Env) -> Result<Vec<Hit>> {
    let db = env.d1("DB")?;
    db.prepare("SELECT path, count FROM hits ORDER BY count DESC")
        .all()
        .await?
        .results::<Hit>()
}

// only count known routes — stops the hits table from being spammed with junk paths
fn valid_path(p: &str) -> bool {
    const KNOWN: [&str; 7] = ["/", "/whoami", "/blog", "/projects", "/uses", "/guestbook", "/stats"];
    if KNOWN.contains(&p) {
        return true;
    }
    if let Some(slug) = p.strip_prefix("/blog/") {
        return !slug.is_empty() && RAW_POSTS.iter().any(|(s, _)| *s == slug);
    }
    false
}

// ---------- request monitor (private /dashboard) ----------

fn should_log(p: &str, dash: &str) -> bool {
    !(p == "/api/hit" || p == "/api/ping" || p.starts_with(dash))
}

// flag common attack-probe paths so they stand out in the log
fn threat_tag(path: &str) -> Option<String> {
    let p = path.to_lowercase();
    const SUS: [&str; 18] = [
        "wp-login", "wp-admin", "xmlrpc", "/.env", "/.git", "phpmyadmin", "/.aws",
        "/.ssh", "/etc/passwd", "/server-status", "/actuator", "/cgi-bin",
        "union select", "<script", "../", "%2e%2e", "/vendor/", "/.vscode",
    ];
    SUS.iter().find(|s| p.contains(*s)).map(|s| s.to_string())
}

async fn log_request(
    db: &D1Database, method: &str, path: &str, status: u16,
    country: &str, ip: &str, ua: &str, threat: Option<String>,
) -> Result<()> {
    let threat_val = match &threat {
        Some(t) => JsValue::from(t.clone()),
        None => JsValue::NULL,
    };
    db.prepare("INSERT INTO requests (method,path,status,country,ip,ua,threat) VALUES (?1,?2,?3,?4,?5,?6,?7)")
        .bind(&[
            JsValue::from(method),
            JsValue::from(clamp(path, 256)),
            JsValue::from_f64(status as f64),
            JsValue::from(country),
            JsValue::from(ip),
            JsValue::from(clamp(ua, 180)),
            threat_val,
        ])?
        .run()
        .await?;
    Ok(())
}

#[derive(Deserialize, Default)]
struct ReqRow {
    method: String,
    path: String,
    status: i64,
    country: String,
    ip: String,
    ua: String,
    threat: Option<String>,
    ts: String,
}

#[derive(Deserialize, Default)]
struct KC {
    k: String,
    c: i64,
}

#[derive(Default)]
struct Dash {
    recent: Vec<ReqRow>,
    total: i64,
    flagged: i64,
    ips: i64,
    day: i64,
    top_paths: Vec<KC>,
    top_countries: Vec<KC>,
}

async fn dashboard_data(env: &Env) -> Result<Dash> {
    let db = env.d1("DB")?;
    let recent = db
        .prepare("SELECT method,path,status,country,ip,ua,threat,ts FROM requests ORDER BY id DESC LIMIT 50")
        .all().await?.results::<ReqRow>()?;
    let total = db.prepare("SELECT COUNT(*) c FROM requests").first::<i64>(Some("c")).await?.unwrap_or(0);
    let flagged = db.prepare("SELECT COUNT(*) c FROM requests WHERE threat IS NOT NULL").first::<i64>(Some("c")).await?.unwrap_or(0);
    let ips = db.prepare("SELECT COUNT(DISTINCT ip) c FROM requests").first::<i64>(Some("c")).await?.unwrap_or(0);
    let day = db.prepare("SELECT COUNT(*) c FROM requests WHERE ts >= datetime('now','-1 day')").first::<i64>(Some("c")).await?.unwrap_or(0);
    let top_paths = db.prepare("SELECT path k, COUNT(*) c FROM requests GROUP BY path ORDER BY c DESC LIMIT 8").all().await?.results::<KC>()?;
    let top_countries = db.prepare("SELECT country k, COUNT(*) c FROM requests GROUP BY country ORDER BY c DESC LIMIT 8").all().await?.results::<KC>()?;
    Ok(Dash { recent, total, flagged, ips, day, top_paths, top_countries })
}

fn field(form: &FormData, key: &str) -> String {
    match form.get(key) {
        Some(FormEntry::Field(s)) => s,
        _ => String::new(),
    }
}

fn clamp(s: &str, n: usize) -> String {
    s.chars().take(n).collect()
}

fn redirect_to(path: &str) -> Result<Response> {
    let h = Headers::new();
    h.set("Location", path)?;
    Ok(Response::empty()?.with_status(303).with_headers(h))
}

// ---------- posts ----------

struct Post {
    slug: String,
    title: String,
    date: String, // YYYY-MM-DD
    description: String,
    tags: Vec<String>,
    body: String,
    minutes: usize,
}

fn parse_post(slug: &str, raw: &str) -> Post {
    let raw = raw.trim_start_matches('\u{feff}');
    let mut title = slug.to_string();
    let mut date = String::new();
    let mut description = String::new();
    let mut tags = Vec::new();
    let body;

    if let Some(rest) = raw.strip_prefix("---") {
        if let Some(end) = rest.find("\n---") {
            let fm = &rest[..end];
            let after = &rest[end + 4..];
            let start = after.find('\n').map(|i| i + 1).unwrap_or(after.len());
            body = after[start..].to_string();
            for line in fm.lines() {
                let line = line.trim();
                if let Some(v) = line.strip_prefix("title:") {
                    title = v.trim().to_string();
                } else if let Some(v) = line.strip_prefix("date:") {
                    date = v.trim().to_string();
                } else if let Some(v) = line.strip_prefix("description:") {
                    description = v.trim().to_string();
                } else if let Some(v) = line.strip_prefix("tags:") {
                    tags = v
                        .trim()
                        .trim_start_matches('[')
                        .trim_end_matches(']')
                        .split(',')
                        .map(|s| s.trim().to_string())
                        .filter(|s| !s.is_empty())
                        .collect();
                }
            }
        } else {
            body = raw.to_string();
        }
    } else {
        body = raw.to_string();
    }

    let minutes = (body.split_whitespace().count() / 200).max(1);
    Post { slug: slug.to_string(), title, date, description, tags, body, minutes }
}

fn all_posts() -> Vec<Post> {
    let mut v: Vec<Post> = RAW_POSTS.iter().map(|(s, r)| parse_post(s, r)).collect();
    v.sort_by(|a, b| b.date.cmp(&a.date));
    v
}

fn find_post(slug: &str) -> Option<Post> {
    RAW_POSTS.iter().find(|(s, _)| *s == slug).map(|(s, r)| parse_post(s, r))
}

fn render_md(md: &str) -> String {
    let mut o = Options::default();
    o.extension.strikethrough = true;
    o.extension.table = true;
    o.extension.autolink = true;
    o.extension.tasklist = true;
    o.extension.footnotes = true;
    o.render.r#unsafe = true;
    markdown_to_html(md, &o)
}

// ---------- helpers ----------

fn esc(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;")
}

fn att(s: &str) -> String {
    esc(s).replace('"', "&quot;")
}

fn short_date(d: &str) -> String {
    let p: Vec<&str> = d.split('-').collect();
    if p.len() == 3 {
        let m = match p[1] {
            "01" => "Jan", "02" => "Feb", "03" => "Mar", "04" => "Apr",
            "05" => "May", "06" => "Jun", "07" => "Jul", "08" => "Aug",
            "09" => "Sep", "10" => "Oct", "11" => "Nov", "12" => "Dec",
            _ => p[1],
        };
        format!("{m} {}", p[0])
    } else if d.is_empty() {
        "—".to_string()
    } else {
        d.to_string()
    }
}

fn tags_html(tags: &[String]) -> String {
    tags.iter().map(|t| format!("<span class=\"tag\">{}</span>", esc(t))).collect::<String>()
}

fn post_row(p: &Post) -> String {
    format!(
        "<li><span class=\"date\">{date}</span><a href=\"/blog/{slug}\">{title}</a>{tags}</li>",
        date = short_date(&p.date),
        slug = p.slug,
        title = esc(&p.title),
        tags = tags_html(&p.tags),
    )
}

// ---------- pages ----------

fn home_page() -> String {
    let posts = all_posts();
    let latest = if posts.is_empty() {
        "<p class=\"out\">Posts coming soon.</p>".to_string()
    } else {
        format!("<ul class=\"posts\">{}</ul>", posts.iter().take(3).map(post_row).collect::<String>())
    };
    let inner = format!("{HOME_TOP}\n<h2>// latest</h2>\n{latest}");
    layout("~", "whoami", SITE_DESC, "/", "", &inner)
}

fn blog_index() -> String {
    let posts = all_posts();
    let list = if posts.is_empty() {
        "<p class=\"out\">No posts yet.</p>".to_string()
    } else {
        format!("<ul class=\"posts\">{}</ul>", posts.iter().map(post_row).collect::<String>())
    };
    let inner = format!(
        "<h1>// blog</h1>\n<p class=\"lead\">Notes, writeups, and the occasional deep dive.</p>\n{list}"
    );
    layout("blog", "blog", "Security writeups, projects, and homelab notes.", "/blog", "", &inner)
}

fn post_page(p: &Post, views: i64) -> String {
    let inner = format!(
        "<a class=\"back\" href=\"/blog\">← all posts</a>\n<h1>{title}</h1>\n\
         <div class=\"post-meta\"><span>{date}</span><span>{min} min read</span>\
         <span>{views} views</span>{tags}</div>\n\
         <article>{body}</article>",
        title = esc(&p.title),
        date = short_date(&p.date),
        min = p.minutes,
        views = views,
        tags = tags_html(&p.tags),
        body = render_md(&p.body),
    );
    let head = "<link rel=\"stylesheet\" href=\"/hljs-github-dark.css\"><script defer src=\"/hljs.min.js\"></script>";
    let desc = if p.description.is_empty() { SITE_DESC } else { p.description.as_str() };
    layout("blog", &p.title, desc, &format!("/blog/{}", p.slug), head, &inner)
}

fn guestbook_page(entries: &[Entry]) -> String {
    let list = if entries.is_empty() {
        "<p class=\"out\">No entries yet — be the first.</p>".to_string()
    } else {
        let rows = entries
            .iter()
            .map(|e| {
                format!(
                    "<li class=\"gb-entry\"><div class=\"gb-head\">\
                     <span class=\"gb-name\">{name}</span>\
                     <span class=\"gb-date\">{date} UTC</span></div>\
                     <p class=\"gb-msg\">{msg}</p></li>",
                    name = esc(&e.name),
                    date = esc(&e.created),
                    msg = esc(&e.message),
                )
            })
            .collect::<String>();
        format!("<ul class=\"gb-list\">{rows}</ul>")
    };
    let inner = format!(
        r#"<h1>// guestbook</h1>
<p class="lead">Leave a mark. Be nice.</p>
<form class="gb-form" method="post" action="/guestbook">
  <input class="gb-input" type="text" name="name" maxlength="50" placeholder="name (optional)" autocomplete="off">
  <input class="hp" type="text" name="website" tabindex="-1" autocomplete="off" aria-hidden="true">
  <textarea class="gb-input" name="message" maxlength="1000" rows="3" placeholder="message…" required></textarea>
  <button class="gb-btn" type="submit">sign</button>
</form>
{list}"#
    );
    layout("guestbook", "guestbook", "Sign the guestbook — say hi.", "/guestbook", "", &inner)
}

fn stats_page(rows: &[Hit]) -> String {
    let total: i64 = rows.iter().map(|h| h.count).sum();
    let list = if rows.is_empty() {
        "<p class=\"out\">No views recorded yet.</p>".to_string()
    } else {
        let items = rows
            .iter()
            .map(|h| {
                format!(
                    "<li><span class=\"date\">{count}</span><a href=\"{p}\">{p}</a></li>",
                    count = h.count,
                    p = esc(&h.path),
                )
            })
            .collect::<String>();
        format!("<ul class=\"posts\">{items}</ul>")
    };
    let inner = format!(
        "<h1>// stats</h1>\n<p class=\"lead\">{total} page views · self-hosted on D1, no third-party trackers.</p>\n{list}"
    );
    layout("", "stats", "Site analytics — self-hosted, privacy-first.", "/stats", "", &inner)
}

fn dashboard_page(d: &Dash, email: &str) -> String {
    let stat = |label: &str, val: i64| {
        format!("<div class=\"stat\"><span class=\"stat-n\">{val}</span><span class=\"stat-l\">{label}</span></div>")
    };
    let stats = format!(
        "<div class=\"stats\">{}{}{}{}</div>",
        stat("total requests", d.total),
        stat("last 24h", d.day),
        stat("unique IPs", d.ips),
        stat("flagged", d.flagged),
    );

    let rows = if d.recent.is_empty() {
        "<tr><td colspan=\"5\" class=\"out\">No requests logged yet.</td></tr>".to_string()
    } else {
        d.recent
            .iter()
            .map(|r| {
                let cls = if r.threat.is_some() { " class=\"sus\"" } else { "" };
                let badge = r
                    .threat
                    .as_deref()
                    .map(|t| format!(" <span class=\"badge\">{}</span>", esc(t)))
                    .unwrap_or_default();
                format!(
                    "<tr{cls}><td>{ts}</td><td>{m}</td><td>{st}</td><td>{cc}</td><td class=\"p\">{path}{badge}</td></tr>",
                    ts = esc(&r.ts), m = esc(&r.method), st = r.status, cc = esc(&r.country), path = esc(&r.path),
                )
            })
            .collect::<String>()
    };
    let table = format!(
        "<table class=\"req\"><thead><tr><th>time (UTC)</th><th>method</th><th>status</th><th>cc</th><th>path</th></tr></thead><tbody>{rows}</tbody></table>"
    );

    let list = |title: &str, items: &[KC]| {
        let body = items
            .iter()
            .map(|k| format!("<li><span class=\"date\">{}</span><span>{}</span></li>", k.c, esc(&k.k)))
            .collect::<String>();
        format!("<h2>// {title}</h2>\n<ul class=\"posts\">{body}</ul>")
    };

    let inner = format!(
        "<h1>// request monitor</h1>\n<p class=\"lead\">Signed in as {email}. Live request log for lunaric.dev.</p>\n{stats}\n<h2>// recent requests</h2>\n{table}\n{tp}\n{tc}",
        email = esc(email),
        tp = list("top paths", &d.top_paths),
        tc = list("top countries", &d.top_countries),
    );
    layout("", "request monitor", "Private request monitor.", "/", "", &inner)
}

fn rss() -> String {
    let items = all_posts()
        .iter()
        .map(|p| {
            format!(
                "<item><title>{t}</title><link>https://lunaric.dev/blog/{s}</link>\
                 <guid>https://lunaric.dev/blog/{s}</guid><pubDate>{d}</pubDate>\
                 <description>{desc}</description></item>",
                t = esc(&p.title),
                s = p.slug,
                d = esc(&p.date),
                desc = esc(&p.description),
            )
        })
        .collect::<String>();
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\
         <rss version=\"2.0\"><channel><title>lunaric.dev</title>\
         <link>https://lunaric.dev</link>\
         <description>Security writeups, projects, and homelab notes.</description>{items}</channel></rss>"
    )
}

fn sitemap() -> String {
    let mut urls = vec![
        "".to_string(),
        "/whoami".into(),
        "/blog".into(),
        "/projects".into(),
        "/uses".into(),
        "/guestbook".into(),
    ];
    for p in all_posts() {
        urls.push(format!("/blog/{}", p.slug));
    }
    let body = urls
        .iter()
        .map(|u| format!("<url><loc>https://lunaric.dev{u}</loc></url>"))
        .collect::<String>();
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\
         <urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">{body}</urlset>"
    )
}

// ---------- layout ----------

fn nav(active: &str) -> String {
    [
        ("whoami", "/whoami"),
        ("blog", "/blog"),
        ("projects", "/projects"),
        ("uses", "/uses"),
        ("guestbook", "/guestbook"),
    ]
    .iter()
    .map(|(label, href)| {
        let cur = if *label == active { " class=\"on\"" } else { "" };
        format!("<a href=\"{href}\"{cur}>{label}</a>")
    })
    .collect::<String>()
}

fn layout(active: &str, title: &str, desc: &str, path: &str, head_extra: &str, inner: &str) -> String {
    let page_title = att(&format!("{title} · lunaric.dev"));
    let desc = att(desc);
    let og_image = match path.strip_prefix("/blog/") {
        Some(slug) if !slug.is_empty() => format!("https://lunaric.dev/og/{slug}.png"),
        _ => "https://lunaric.dev/og/default.png".to_string(),
    };
    format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{pt}</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="https://lunaric.dev{path}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="lunaric.dev">
<meta property="og:title" content="{pt}">
<meta property="og:description" content="{desc}">
<meta property="og:url" content="https://lunaric.dev{path}">
<meta property="og:image" content="{og_image}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:creator" content="@11lunaric11">
<meta name="twitter:title" content="{pt}">
<meta name="twitter:description" content="{desc}">
<meta name="twitter:image" content="{og_image}">
<link rel="alternate" type="application/rss+xml" title="lunaric.dev" href="/rss.xml">
<script src="/theme.js"></script>
<link rel="stylesheet" href="/fonts.css">
<link rel="stylesheet" href="/styles.css">
{head_extra}
</head>
<body>
<div class="wrap">
<nav><a class="brand" href="/">lunaric</a><span class="nav-links">{nav}</span></nav>
<main>
{inner}
</main>
<footer>
<span>© 2026 Dejan · built in rust</span>
<a href="/rss.xml">rss</a>
<a href="/stats">stats</a>
<a href="https://github.com/11lunaric11">github</a>
<span class="spacer"><span id="clock">--:--:--</span></span>
</footer>
</div>
<script defer src="/term.js"></script>
</body>
</html>"#,
        pt = page_title,
        desc = desc,
        nav = nav(active),
    )
}

// ---------- static page content ----------

const SITE_DESC: &str =
    "Dejan (lunaric) — offensive security learner, bug bounty hunter, homelab tinkerer.";

const HOME_TOP: &str = r#"<h1>whoami <span class="accent">// lunaric</span></h1>
<p class="lead">Dejan — aka lunaric. Offensive security learner, bug bounty hunter, homelab tinkerer.</p>
<p>I break things to understand them, automate the boring parts, and build whatever I need to learn next. This whole site is hand-written in Rust, compiled to WebAssembly, and served from Cloudflare's edge.</p>

<section class="term">
  <div class="term-bar"><span class="dot r"></span><span class="dot y"></span><span class="dot g"></span><span class="title">lunaric@dev: ~</span></div>
  <div class="term-body" id="term-body">
    <div class="line out">type 'help' to list commands.</div>
    <div class="line" id="term-input-line"><span class="prompt">lunaric@dev</span>:<span class="path">~</span>$&nbsp;<input id="term-input" autocomplete="off" spellcheck="false" aria-label="terminal input"></div>
  </div>
</section>"#;

const WHOAMI: &str = r#"<h1>// whoami</h1>
<p class="lead">Dejan — aka lunaric. Offensive security learner, bug bounty hunter, homelab tinkerer.</p>
<p>I'm into offensive security and red teaming — currently grinding through TryHackMe and Hack The Box certs and hunting bugs on the side (a handful of valid findings so far). I break things to understand them, automate the boring parts, and build whatever I want to learn next. This site is one of those builds.</p>

<h2>// certs</h2>
<ul class="posts">
  <li><span class="date">Jun 2026</span><span>PT1 — TryHackMe <span class="accent">✓</span></span><span class="tag">THM</span></li>
  <li><span class="date">Jun 2026</span><span>AI1 — TryHackMe <span class="accent">✓</span></span><span class="tag">THM</span></li>
  <li><span class="date">Apr 2026</span><span>SEC1 — TryHackMe <span class="accent">✓</span></span><span class="tag">THM</span></li>
  <li><span class="date">Apr 2026</span><span>SEC0 — TryHackMe <span class="accent">✓</span></span><span class="tag">THM</span></li>
  <li><span class="date">planned</span><span>CJCA — Hack The Box</span><span class="tag">HTB</span></li>
  <li><span class="date">planned</span><span>CPTS — Hack The Box</span><span class="tag">HTB</span></li>
</ul>

<h2>// focus</h2>
<p>Web app · Network · Active Directory · Cloud · CTFs · Self-hosting · Reverse engineering · Red team.</p>

<h2>// links</h2>
<ul class="links">
  <li><a href="https://github.com/11lunaric11">GitHub</a></li>
  <li><a href="https://tryhackme.com/p/lunaricdev11">TryHackMe</a></li>
  <li><a href="https://app.hackthebox.com/users/3372567">Hack The Box</a></li>
  <li><a href="https://x.com/11lunaric11">X</a></li>
  <li><a href="https://www.linkedin.com/in/dejan-schult">LinkedIn</a></li>
  <li><a href="mailto:contact@lunaric.dev">contact@lunaric.dev</a></li>
  <li><span class="dc">Discord: __lunaric__</span></li>
</ul>"#;

const PROJECTS: &str = r#"<h1>// projects</h1>
<p class="lead">Things I've built and broken. More on <a href="https://github.com/11lunaric11">GitHub</a>.</p>
<ul class="posts">
  <li><span class="date">2026</span><a href="https://github.com/11lunaric11/lunaric.dev">lunaric.dev</a><span class="tag">rust</span><span class="tag">wasm</span><span class="tag">cloudflare</span></li>
</ul>"#;

const USES: &str = r#"<h1>// uses</h1>
<p class="lead">The gear and setup behind the homelab.</p>

<h2>// workstation</h2>
<ul class="posts">
  <li><span class="date">cpu</span><span>Intel Core Ultra 5 245KF — 14 cores @ 5.20 GHz</span></li>
  <li><span class="date">gpu</span><span>AMD Radeon RX 9070 XT</span></li>
  <li><span class="date">ram</span><span>32 GB</span></li>
  <li><span class="date">os</span><span>Parrot OS — Security Edition</span></li>
</ul>

<h2>// homelab</h2>
<ul class="posts">
  <li><span class="date">vps</span><span>VPS running automation scripts &amp; tooling</span></li>
</ul>

<h2>// on the wishlist</h2>
<ul class="posts">
  <li><span class="date">soon</span><span>Zimaboard — a low-power, always-on lab node</span></li>
  <li><span class="date">soon</span><span>Local AI / inference hardware</span></li>
</ul>"#;
