//! lunaric.dev — a personal security/dev blog.
//! Hand-written in Rust, compiled to WebAssembly, served from Cloudflare's edge.

use comrak::{markdown_to_html, Options};
use worker::*;

// Generated by build.rs: `RAW_POSTS: &[(&str, &str)]` of (slug, raw markdown).
include!(concat!(env!("OUT_DIR"), "/posts_generated.rs"));

#[event(fetch)]
async fn fetch(req: Request, env: Env, _ctx: Context) -> Result<Response> {
    console_error_panic_hook::set_once();

    Router::new()
        .get("/", |_, _| Response::from_html(home_page()))
        .get("/whoami", |_, _| Response::from_html(layout("whoami", "whoami", "", WHOAMI)))
        .get("/blog", |_, _| Response::from_html(blog_index()))
        .get("/blog/:slug", |_, ctx| match ctx.param("slug").and_then(|s| find_post(s)) {
            Some(p) => Response::from_html(post_page(&p)),
            None => Response::error("Post not found", 404),
        })
        .get("/projects", |_, _| Response::from_html(layout("projects", "projects", "", PROJECTS)))
        .get("/uses", |_, _| Response::from_html(layout("uses", "uses", "", USES)))
        .get("/rss.xml", |_, _| {
            let mut r = Response::ok(rss())?;
            r.headers_mut().set("content-type", "application/rss+xml; charset=utf-8")?;
            Ok(r)
        })
        .get_async("/api/ping", |_, _| async move {
            let body = r#"{"status":"ok","host":"lunaric.dev","runtime":"rust+wasm @ cloudflare edge"}"#;
            let mut resp = Response::ok(body)?;
            resp.headers_mut().set("content-type", "application/json")?;
            Ok(resp)
        })
        .run(req, env)
        .await
}

// ---------- posts ----------

struct Post {
    slug: String,
    title: String,
    date: String, // YYYY-MM-DD
    description: String,
    tags: Vec<String>,
    body: String,
    minutes: usize,
}

fn parse_post(slug: &str, raw: &str) -> Post {
    let raw = raw.trim_start_matches('\u{feff}');
    let mut title = slug.to_string();
    let mut date = String::new();
    let mut description = String::new();
    let mut tags = Vec::new();
    let body;

    if let Some(rest) = raw.strip_prefix("---") {
        if let Some(end) = rest.find("\n---") {
            let fm = &rest[..end];
            let after = &rest[end + 4..];
            let start = after.find('\n').map(|i| i + 1).unwrap_or(after.len());
            body = after[start..].to_string();
            for line in fm.lines() {
                let line = line.trim();
                if let Some(v) = line.strip_prefix("title:") {
                    title = v.trim().to_string();
                } else if let Some(v) = line.strip_prefix("date:") {
                    date = v.trim().to_string();
                } else if let Some(v) = line.strip_prefix("description:") {
                    description = v.trim().to_string();
                } else if let Some(v) = line.strip_prefix("tags:") {
                    tags = v
                        .trim()
                        .trim_start_matches('[')
                        .trim_end_matches(']')
                        .split(',')
                        .map(|s| s.trim().to_string())
                        .filter(|s| !s.is_empty())
                        .collect();
                }
            }
        } else {
            body = raw.to_string();
        }
    } else {
        body = raw.to_string();
    }

    let minutes = (body.split_whitespace().count() / 200).max(1);
    Post { slug: slug.to_string(), title, date, description, tags, body, minutes }
}

fn all_posts() -> Vec<Post> {
    let mut v: Vec<Post> = RAW_POSTS.iter().map(|(s, r)| parse_post(s, r)).collect();
    v.sort_by(|a, b| b.date.cmp(&a.date));
    v
}

fn find_post(slug: &str) -> Option<Post> {
    RAW_POSTS.iter().find(|(s, _)| *s == slug).map(|(s, r)| parse_post(s, r))
}

fn render_md(md: &str) -> String {
    let mut o = Options::default();
    o.extension.strikethrough = true;
    o.extension.table = true;
    o.extension.autolink = true;
    o.extension.tasklist = true;
    o.extension.footnotes = true;
    o.render.r#unsafe = true;
    markdown_to_html(md, &o)
}

// ---------- helpers ----------

fn esc(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;")
}

fn short_date(d: &str) -> String {
    let p: Vec<&str> = d.split('-').collect();
    if p.len() == 3 {
        let m = match p[1] {
            "01" => "Jan", "02" => "Feb", "03" => "Mar", "04" => "Apr",
            "05" => "May", "06" => "Jun", "07" => "Jul", "08" => "Aug",
            "09" => "Sep", "10" => "Oct", "11" => "Nov", "12" => "Dec",
            _ => p[1],
        };
        format!("{m} {}", p[0])
    } else if d.is_empty() {
        "—".to_string()
    } else {
        d.to_string()
    }
}

fn tags_html(tags: &[String]) -> String {
    tags.iter().map(|t| format!("<span class=\"tag\">{}</span>", esc(t))).collect::<String>()
}

fn post_row(p: &Post) -> String {
    format!(
        "<li><span class=\"date\">{date}</span><a href=\"/blog/{slug}\">{title}</a>{tags}</li>",
        date = short_date(&p.date),
        slug = p.slug,
        title = esc(&p.title),
        tags = tags_html(&p.tags),
    )
}

// ---------- pages ----------

fn home_page() -> String {
    let posts = all_posts();
    let latest = if posts.is_empty() {
        "<p class=\"out\">Posts coming soon.</p>".to_string()
    } else {
        format!(
            "<ul class=\"posts\">{}</ul>",
            posts.iter().take(3).map(post_row).collect::<String>()
        )
    };
    let inner = format!("{HOME_TOP}\n<h2>// latest</h2>\n{latest}");
    layout("~", "whoami", "", &inner)
}

fn blog_index() -> String {
    let posts = all_posts();
    let list = if posts.is_empty() {
        "<p class=\"out\">No posts yet.</p>".to_string()
    } else {
        format!("<ul class=\"posts\">{}</ul>", posts.iter().map(post_row).collect::<String>())
    };
    let inner = format!(
        "<h1>// blog</h1>\n<p class=\"lead\">Notes, writeups, and the occasional deep dive.</p>\n{list}"
    );
    layout(
        "blog",
        "blog",
        "<link rel=\"alternate\" type=\"application/rss+xml\" title=\"lunaric.dev\" href=\"/rss.xml\">",
        &inner,
    )
}

fn post_page(p: &Post) -> String {
    let inner = format!(
        "<a class=\"back\" href=\"/blog\">← all posts</a>\n<h1>{title}</h1>\n\
         <div class=\"post-meta\"><span>{date}</span><span>{min} min read</span>{tags}</div>\n\
         <article>{body}</article>",
        title = esc(&p.title),
        date = short_date(&p.date),
        min = p.minutes,
        tags = tags_html(&p.tags),
        body = render_md(&p.body),
    );
    let head = "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css\"><script defer src=\"https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js\" onload=\"hljs.highlightAll()\"></script>";
    layout("blog", &p.title, head, &inner)
}

fn rss() -> String {
    let items = all_posts()
        .iter()
        .map(|p| {
            format!(
                "<item><title>{t}</title><link>https://lunaric.dev/blog/{s}</link>\
                 <guid>https://lunaric.dev/blog/{s}</guid><pubDate>{d}</pubDate>\
                 <description>{desc}</description></item>",
                t = esc(&p.title),
                s = p.slug,
                d = esc(&p.date),
                desc = esc(&p.description),
            )
        })
        .collect::<String>();
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\
         <rss version=\"2.0\"><channel><title>lunaric.dev</title>\
         <link>https://lunaric.dev</link>\
         <description>Security writeups, projects, and homelab notes.</description>{items}</channel></rss>"
    )
}

// ---------- layout ----------

fn nav(active: &str) -> String {
    [("whoami", "/whoami"), ("blog", "/blog"), ("projects", "/projects"), ("uses", "/uses")]
        .iter()
        .map(|(label, href)| {
            let cur = if *label == active { " style=\"color:var(--teal)\"" } else { "" };
            format!("<a href=\"{href}\"{cur}>{label}</a>")
        })
        .collect::<String>()
}

fn layout(active: &str, title: &str, head_extra: &str, inner: &str) -> String {
    format!(
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} · lunaric.dev</title>
<meta name="description" content="lunaric — security learner, bug bounty hunter, homelab tinkerer.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/styles.css">
{head_extra}
</head>
<body>
<div class="wrap">
<nav><a class="brand" href="/">lunaric</a>{nav}</nav>
<main>
{inner}
</main>
<footer>
<span>© 2026 Dejan · built in rust</span>
<a href="/rss.xml">rss</a>
<a href="https://github.com/11lunaric11">github</a>
<span class="spacer">Berlin <span id="clock">--:--:--</span></span>
</footer>
</div>
<script src="/term.js"></script>
</body>
</html>"#,
        nav = nav(active)
    )
}

// ---------- static page content ----------

const HOME_TOP: &str = r#"<h1>whoami <span class="accent">// lunaric</span></h1>
<p class="lead">Dejan — aka lunaric. Offensive security learner, bug bounty hunter, homelab tinkerer.</p>
<p>I break things to understand them, automate the boring parts, and build whatever I need to learn next. This whole site is hand-written in Rust, compiled to WebAssembly, and served from Cloudflare's edge.</p>

<section class="term">
  <div class="term-bar"><span class="dot r"></span><span class="dot y"></span><span class="dot g"></span><span class="title">lunaric@dev: ~</span></div>
  <div class="term-body" id="term-body">
    <div class="line out">type 'help' to list commands.</div>
    <div class="line" id="term-input-line"><span class="prompt">lunaric@dev</span>:<span class="path">~</span>$&nbsp;<input id="term-input" autocomplete="off" spellcheck="false" aria-label="terminal input"></div>
  </div>
</section>"#;

const WHOAMI: &str = r#"<h1>// whoami</h1>
<p class="lead">Dejan — aka lunaric. Offensive security learner, bug bounty hunter, homelab tinkerer.</p>
<p>I'm into offensive security and red teaming — currently grinding through TryHackMe and Hack The Box certs and hunting bugs on the side (a handful of valid findings so far). I break things to understand them, automate the boring parts, and build whatever I want to learn next. This site is one of those builds.</p>

<h2>// certs</h2>
<ul class="posts">
  <li><span class="date">Jun 2026</span><span>PT1 — TryHackMe <span class="accent">✓</span></span><span class="tag">THM</span></li>
  <li><span class="date">Jun 2026</span><span>AI1 — TryHackMe <span class="accent">✓</span></span><span class="tag">THM</span></li>
  <li><span class="date">Apr 2026</span><span>SEC1 — TryHackMe <span class="accent">✓</span></span><span class="tag">THM</span></li>
  <li><span class="date">Apr 2026</span><span>SEC0 — TryHackMe <span class="accent">✓</span></span><span class="tag">THM</span></li>
  <li><span class="date">planned</span><span>CJCA — Hack The Box</span><span class="tag">HTB</span></li>
  <li><span class="date">planned</span><span>CPTS — Hack The Box</span><span class="tag">HTB</span></li>
</ul>

<h2>// focus</h2>
<p>Web app · Network · Active Directory · Cloud · CTFs · Self-hosting · Reverse engineering · Red team.</p>

<h2>// links</h2>
<ul class="links">
  <li><a href="https://github.com/11lunaric11">GitHub</a></li>
  <li><a href="https://tryhackme.com/p/lunaricdev11">TryHackMe</a></li>
  <li><a href="https://app.hackthebox.com/users/3372567">Hack The Box</a></li>
  <li><a href="https://x.com/11lunaric11">X</a></li>
  <li><a href="https://www.linkedin.com/in/dejan-schult">LinkedIn</a></li>
  <li><a href="mailto:contact@lunaric.dev">contact@lunaric.dev</a></li>
  <li><span class="dc">Discord: __lunaric__</span></li>
</ul>"#;

const PROJECTS: &str = r#"<h1>// projects</h1>
<p class="lead">Things I've built and broken. More on <a href="https://github.com/11lunaric11">GitHub</a>.</p>
<ul class="posts">
  <li><span class="date">2026</span><a href="https://github.com/11lunaric11">lunaric.dev</a><span class="tag">rust</span><span class="tag">wasm</span><span class="tag">cloudflare</span></li>
</ul>"#;

const USES: &str = r#"<h1>// uses</h1>
<p class="lead">The gear and setup behind the homelab.</p>

<h2>// workstation</h2>
<ul class="posts">
  <li><span class="date">cpu</span><span>Intel Core Ultra 5 245KF — 14 cores @ 5.20 GHz</span></li>
  <li><span class="date">gpu</span><span>AMD Radeon RX 9070 XT</span></li>
  <li><span class="date">ram</span><span>32 GB</span></li>
  <li><span class="date">os</span><span>Parrot OS — Security Edition</span></li>
</ul>

<h2>// homelab</h2>
<ul class="posts">
  <li><span class="date">vps</span><span>VPS running automation scripts &amp; tooling</span></li>
</ul>

<h2>// on the wishlist</h2>
<ul class="posts">
  <li><span class="date">soon</span><span>Zimaboard — a low-power, always-on lab node</span></li>
  <li><span class="date">soon</span><span>Local AI / inference hardware</span></li>
</ul>"#;
